server:
  port: 8083

spring:
  cloud:
    nacos:
      server-addr: 60.204.208.219:80
  application:
    name: workspaceService
  redis:
    host: 60.204.208.219
    port: 6379
    timeout: 50000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 50
        min-idle: 5

logging:
  level:
    com.bdilab: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

